version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "33060:33061"
  redis:
    image: redis
    command: redis-server --port 6679
    ports:
      - "6679:6679"
  elasticsearch:
    image: elasticsearch:6.5.1
    ports:
      - "9200:9200"
  sidekiq:
    build: .
    image: sidekiq:6.4.2
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
  web:
    build: .
    command:  bash -c "rm -f tmp/pids/server.pid && ./init.sh"
    volumes:
      - .:/myapp
    ports:
     - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - sidekiq





